### PR TITLE
Added a progress bar to the installer

### PR DESCRIPTION
**Pull request by TheAio**
Added a progress bar to the installer,
users now get a progress bar indicating how many more inputs they have to make.

### CODE REVIEW

**Comment by XDuskAshes** [comment]
This is actually a good idea and improves the user experience. I'll fully merge this once I have everything setup on my local, I still have to fidget with git for a bit to get auth to work.

**Comment by TheAio** [comment]
Yeah thanks :D
Don't worry too much about hurrying.

**Comment by XDuskAshes** [comment]
Almost done fidgeting with auth crap, you should contribute more. This looks really nice.

**Comment by TheAio** [comment]
Thank you,
i accepted your discord friend request btw :)

**Pull request merged**
