### PR TITLE
Include support for dash.conf

### PR DESCRIPTION
**Pull request by TheAio**
Include support for dash.conf,
this will allow the user to setup auto running files when dash opens and will allow users to input commands to dash via a file. This is useful for example if some software should be allowed to take control over user inputs, such as a desktop environment. The file that causes user inputs is limited to the same restrictions as the user, so it still has to be root for root level calls.

### CODE REVIEW

**Comment by TheAio** [comment]
example dash.conf file could be
`useFileBasedInputs:
true
fileBasedInputPath:
/tmp/dash-input.temp
runFolderAtStart = true
startFolderPath = "/bin/someDesktopEnvormentFolder/"`

**Comment by XDuskAshes** [comment]
While this is a really good idea, I was more going for something like a ``.bashrc`` file, where it's per home directory. ``dash.conf`` is still a good filename, it would just be more economical to have the per-user config instead of default configs.

**Comment by TheAio** [comment]
Yeah per user configs would definitely be better, it's just a slightly bigger challenge given the structure of the filesystem but should be possible.

**Comment by XDuskAshes** [comment]
It's based off FHS (Filesystem Hierarchy Standard), and so is linux, so could do similar
would have to make an ``fs`` module to the kernel though :p

**Comment by TheAio** [comment]
I made a quick issue #4 to keep track of this.
I think we can make it work, it might just take some time to figure it out :)

**Comment by XDuskAshes** [comment]
pr denied, working on ``.dashrc`` and such instead.

**Pull request closed without merging**
